version: '3.0'

services:
  php:
    container_name: comebackpw-parser-php
    build:
      context: ./docker/
      dockerfile: php/Dockerfile
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - backend
networks:
  backend:
